In [ ]:
import torch
print(torch.__version__)


2.4.1+cu121


In [ ]:
x=torch.Tensor(10).random_(0,10)
x.to("cpu")

tensor([0., 9., 2., 3., 8., 3., 8., 9., 9., 3.])

In [ ]:
cuda_available=torch.cuda.is_available()
cuda_available

False

In [ ]:
import torch
one_d_tensor=torch.zeros(4)
two_d_tensor=torch.zeros(1,4)
print(f"This is one d tensor{one_d_tensor} with shape{one_d_tensor.shape}")
print(f"This is TWO d tensor{two_d_tensor} with shape{two_d_tensor.shape}")



This is one d tensortensor([0., 0., 0., 0.]) with shapetorch.Size([4])
This is TWO d tensortensor([[0., 0., 0., 0.]]) with shapetorch.Size([1, 4])


In [ ]:
two=torch.ones((23,3))
two.shape,two

(torch.Size([23, 3]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
two=torch.ones((2,3,3))
two.shape,two

(torch.Size([2, 3, 3]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [15]:
example_1 = torch.randn(3,3)
example_2 = torch.randint(low=0, high=2, \
size=(3,3)).type(torch.FloatTensor)

In [18]:
pip install ucimlrepo

In [19]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
appliances_energy_prediction = fetch_ucirepo(id=374)

# data (as pandas dataframes)
X = appliances_energy_prediction.data.features
y = appliances_energy_prediction.data.targets

# metadata
print(appliances_energy_prediction.metadata)

# variable information
print(appliances_energy_prediction.variables)


{'uci_id': 374, 'name': 'Appliances Energy Prediction', 'repository_url': 'https://archive.ics.uci.edu/dataset/374/appliances+energy+prediction', 'data_url': 'https://archive.ics.uci.edu/static/public/374/data.csv', 'abstract': 'Experimental data used to create regression models of appliances energy use in a low energy building.', 'area': 'Computer Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate', 'Time-Series'], 'num_instances': 19735, 'num_features': 28, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Appliances'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2017, 'last_updated': 'Fri Mar 29 2024', 'dataset_doi': '10.24432/C5VC8G', 'creators': ['Luis Candanedo'], 'intro_paper': {'ID': 398, 'type': 'NATIVE', 'title': 'Data driven prediction models of energy use of appliances in a low-energy house', 'authors': 'L. Candanedo, V. Feldheim, Dominique Deramaix', 'venue': 'Energy and Buildings,

In [29]:
pip install pandas


In [32]:
# Most Commonly used method of fetching data
path = "energydata_complete.csv"
df = pd.read_csv(path)
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [33]:
df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [34]:
df.index

RangeIndex(start=0, stop=19735, step=1)

In [37]:
import torch
list_a=[1,2,3,4]
tensor=torch.tensor(list_a)
print(tensor)

tensor([1, 2, 3, 4])


In [39]:
import numpy as np
import torch
arr_a=[1,2,3,4]
arr_b=[5,6,7,8]
tensora=torch.tensor(arr_a)
tensorb=torch.tensor(arr_b)
tensor_c=tensorb-tensora
tensor_d=tensora*tensorb
tensor_e=tensor_c+tensor_d
print(tensor_e)

tensor([ 9, 16, 25, 36])


In [41]:
import torch.nn as nn
input_tensor=torch.tensor([[1.22,0.32,4.55]])
linear_layer=nn.Linear(in_features=3,out_features=2)
out=linear_layer(input_tensor)
print(out)

tensor([[-2.2725,  2.9284]], grad_fn=<AddmmBackward0>)


In [43]:
linear_layer.weight
linear_layer.bias

Parameter containing:
tensor([0.2536, 0.3020], requires_grad=True)

In [55]:
import torch.nn as nn

class SimpleNN(nn.Module):
  def __init__(self, hidden_units):
     super(SimpleNN,self).__init__()
     self.linear_layer1=nn.Linear(8,hidden_units)
     self.linear_layer2=nn.Linear(hidden_units,1)
  def forward(self,x):
     # Convert the input tensor to float32 before passing it to the linear layer
     x = x.type(torch.float32)
     x=torch.relu(self.linear_layer1(x))
     x=self.linear_layer2(x)
     return x

hidden_units=4
model=SimpleNN(hidden_units)
input_tensor=torch.tensor([[2, 3, 6, 7, 9, 3, 2, 1]])
output = model(input_tensor)
print("Output:", output)


Output: tensor([[-0.5206]], grad_fn=<AddmmBackward0>)


In [61]:
import torch
import torch.nn as nn
class module(nn.Module):
  def __init__(self):
    super(module,self).__init__()
    self.l1=nn.Linear(12,16)
    self.l2=nn.Linear(16,8)
    self.l3=nn.Linear(8,4)
    self.l4=nn.Linear(4,1)
  def forward(self,x):
    x=torch.relu(self.l1(x))
    x=torch.relu(self.l2(x))
    x=torch.relu(self.l3(x))
    x=self.l4(x)
    return(x)
model = module()
input=torch.Tensor([[9,8,7,6,5,4,3,2,1,16,12,22]])
out=model(input)
print(out)



tensor([[0.5260]], grad_fn=<AddmmBackward0>)


In [70]:
import torch
import torch.nn as nn
score=torch.Tensor([[1.5,2.5,-1.5,2,3]])
sig=torch.sigmoid(score)
print(sig)
soft=nn.Softmax(dim=1)
out=soft(score)
print(out)

tensor([[0.8176, 0.9241, 0.1824, 0.8808, 0.9526]])
tensor([[0.1010, 0.2746, 0.0050, 0.1666, 0.4528]])


In [75]:
import torch
import torch.nn as nn
class binaryClassifier(nn.Module):
  def __init__(self):
    super(binaryClassifier,self).__init__()
    self.l1=nn.Linear(8,1)
  def forward(self,x):
     x=self.l1(x)
     x=torch.sigmoid(x)
     return x
model=binaryClassifier()
input=torch.tensor([[1,2,3,4,5,6,7,8]],dtype=torch.float)
output=model(input)
print(output)


tensor([[0.4310]], grad_fn=<SigmoidBackward0>)


In [80]:
import torch
import torch.nn as nn

class Regression(nn.Module):
    def __init__(self):
        super(Regression, self).__init__()
        self.l1 = nn.Linear(12, 16)  # Input size: 12
        self.l2 = nn.Linear(16, 8)
        self.l3 = nn.Linear(8, 4)
        self.l4 = nn.Linear(4, 1)

    def forward(self, x):
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.l4(x)
        return x

# Instantiate the model
model = Regression()

# Prepare an input tensor with the correct size (12 elements)
input_tensor = torch.tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9, 1]], dtype=torch.float)  # Example input with 12 elements

# Perform a forward pass to get the output
output = model(input_tensor)

# Print the output
print("Regression Output:", output.item())


Regression Output: 0.9001694917678833


In [83]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class multiclass(nn.Module):
    def __init__(self):
        super(multiclass, self).__init__()
        self.l1 = nn.Linear(12, 16)  # Input size: 12
        self.l2 = nn.Linear(16, 8)
        self.l3 = nn.Linear(8, 4)
        self.l4 = nn.Linear(4, 1)

    def forward(self, x):
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.l4(x)
        return x

# Instantiate the model
model = multiclass()

# Prepare an input tensor with the correct size (12 elements)
input_tensor = torch.tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9, 1]], dtype=torch.float)  # Example input with 12 elements

# Perform a forward pass to get the output
output = model(input_tensor)
probabilities = F.softmax(output, dim=1)


print("Classification Probabilities:",probabilities)


# Print the output
print("multi class Output:", output)


Classification Probabilities: tensor([[1.]], grad_fn=<SoftmaxBackward0>)
multi class Output: tensor([[-1.9582]], grad_fn=<AddmmBackward0>)


In [85]:
import numpy as np
import torch
import torch.nn.functional as F
y=1
classes=3
one_hot_manual=np.zeros(classes)
one_hot_manual[y]=1
print(one_hot_manual)
tensory=torch.tensor(y)
one_hot_torch=F.one_hot(tensory,num_classes=classes)
print(one_hot_torch)

[0. 1. 0.]
tensor([0, 1, 0])


In [91]:
import torch
import torch.nn.functional as F
y=1
classes=3
torchy=torch.tensor(y)
one_hot1=F.one_hot(tensory,classes),float()
print(one_hot1)
model=torch.tensor([[2.0,5.0,6.0]])
cross_entropy=torch.nn.CrossEntropyLoss()
loss=cross_entropy(model.squeeze(0),torchy)
print(loss)

(tensor([0, 1, 0]), 0.0)
tensor(1.3266)


In [95]:
import torch
import torch.nn.functional as F

# Given ground truth label (e.g., class 1)
y = 1  # The label for the ground truth
num_classes = 3  # Total number of classes

# Step 1: Create the one-hot encoded vector (for reference)
one_hot_label = F.one_hot(torch.tensor(y), num_classes=num_classes).float()
print("One-Hot Encoded Label:", one_hot_label)

# Step 2: Create model scores (logits)
model_scores = torch.tensor([2.0, 0.5, 1.5])  # Example scores (logits)

# Step 3: Create the cross-entropy loss function and store it as criterion
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Calculate the loss using the scores and the ground truth label
# CrossEntropyLoss expects the true labels as class indices (not one-hot encoded)
loss = criterion(model_scores.unsqueeze(0), torch.tensor([y]))  # Add batch dimension
print("Cross Entropy Loss:", loss.item())


One-Hot Encoded Label: tensor([0., 1., 0.])
Cross Entropy Loss: 2.104130744934082


In [102]:
import torch
import torch.nn.functional as F

# Step 1: Define the target class index (ground truth label)
y = 1  # Class index for the target (class 1)

# Step 2: Create the scores (logits) for 4 classes
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])  # Example logits for 4 classes (batch size = 1)

# Step 3: Initialize the cross-entropy loss function
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Convert the target label into a tensor and calculate cross-entropy loss
torchy = torch.tensor([y])  # Must be a tensor with class indices, not one-hot encoding
loss = criterion(scores, torchy)  # Pass raw logits and target class index

# Step 5: Print the cross-entropy loss
print("Cross Entropy Loss:", loss.item())


Cross Entropy Loss: 0.061927277594804764


In [103]:
import torch
import torch.nn as nn
import torch.optim as optim

# Step 1: Define a simple neural network with one linear layer
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(4, 4)  # Input size = 4, output size = 4 (for 4 classes)

    def forward(self, x):
        return self.fc(x)

# Step 2: Instantiate the model, loss function, and optimizer
model = SimpleModel()
criterion = nn.CrossEntropyLoss()  # Cross-entropy loss for classification
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Simple stochastic gradient descent optimizer

# Step 3: Define input (logits) and target (class index) tensors
input_tensor = torch.tensor([[0.1, 6.0, -2.0, 3.2]], requires_grad=True)  # Logits (before softmax)
target = torch.tensor([1])  # Ground truth class (class index)

# Step 4: Perform a forward pass to calculate the loss
output = model(input_tensor)  # Forward pass (logits from the model)
loss = criterion(output, target)  # Calculate cross-entropy loss

# Step 5: Perform a backward pass to compute gradients
loss.backward()  # Backpropagation to compute gradients

# Step 6: Display the gradients of the weights and biases
print("Gradients of the weights:")
print(model.fc.weight.grad)  # Gradients of the weight tensor

print("\nGradients of the biases:")
print(model.fc.bias.grad)  # Gradients of the bias tensor


Gradients of the weights:
tensor([[ 6.1584e-04,  3.6950e-02, -1.2317e-02,  1.9707e-02],
        [-7.5558e-02, -4.5335e+00,  1.5112e+00, -2.4179e+00],
        [ 6.7028e-05,  4.0217e-03, -1.3406e-03,  2.1449e-03],
        [ 7.4876e-02,  4.4925e+00, -1.4975e+00,  2.3960e+00]])

Gradients of the biases:
tensor([ 6.1584e-03, -7.5558e-01,  6.7028e-04,  7.4876e-01])


In [104]:
import torch
import torch.nn as nn

# Step 1: Define a model with two linear layers using nn.Sequential()
model = nn.Sequential(
    nn.Linear(8, 16),  # First Linear layer (input: 8, output: 16)
    nn.Linear(16, 4)   # Second Linear layer (input: 16, output: 4)
)

# Step 2: Access the weight parameter of the first linear layer
first_layer_weight = model[0].weight  # model[0] is the first linear layer
print("Weight of the first linear layer:")
print(first_layer_weight)

# Step 3: Access the bias parameter of the second linear layer
second_layer_bias = model[1].bias  # model[1] is the second linear layer
print("\nBias of the second linear layer:")
print(second_layer_bias)


Weight of the first linear layer:
Parameter containing:
tensor([[ 0.2090,  0.1939, -0.0923,  0.0324,  0.2038, -0.2465,  0.0321, -0.1891],
        [ 0.3328,  0.0482, -0.2629, -0.0806, -0.1453,  0.2563, -0.3028,  0.0915],
        [ 0.2898, -0.2348, -0.0013, -0.0115,  0.1215,  0.1936,  0.0333,  0.0570],
        [-0.2092,  0.0286, -0.2555,  0.0169, -0.0517,  0.0135, -0.2701, -0.2065],
        [-0.2822, -0.2350, -0.0938,  0.2525, -0.3129, -0.0064,  0.3424,  0.3345],
        [ 0.2951,  0.2321,  0.2948,  0.1969, -0.1840, -0.1831,  0.1957,  0.2860],
        [ 0.2859,  0.2910, -0.0497,  0.1248, -0.0664,  0.2161,  0.1215,  0.3334],
        [-0.3371,  0.0869, -0.2227, -0.3484, -0.3522, -0.2602,  0.3310,  0.1904],
        [ 0.2974,  0.2366,  0.2173,  0.1667, -0.2976, -0.3172,  0.2820, -0.1169],
        [-0.3524, -0.3477,  0.0047,  0.0038, -0.3410, -0.1109, -0.1970, -0.0179],
        [ 0.0031, -0.0708,  0.1016,  0.2746,  0.3194,  0.2265,  0.2784, -0.1119],
        [-0.2387, -0.0463, -0.0377, -0.256

In [107]:
import torch
import torch.nn as nn

# Step 1: Define a simple model with three layers
model = nn.Sequential(
    nn.Linear(8, 16),  # First linear layer
    nn.Linear(16, 12),  # Second linear layer
    nn.Linear(12, 4)   # Third linear layer (output size 4)
)

# Step 2: Define a learning rate
lr = 0.01  # Learning rate

# Let's assume we already have a loss and computed its gradients using backward
# loss.backward() should have been called before accessing the gradients

# Step 3: Manually update the weights using the computed gradients
with torch.no_grad():  # Ensure gradients are not tracked during this operation
    for param in model.parameters():
        param -= lr * param.grad  # Subtract scaled gradient from the parameters (weights/biases)

# Clear the gradients after updating (as would be done by the optimizer)
model.zero_grad()


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [108]:
import torch
import torch.nn as nn

# Define a simple model with three linear layers
model = nn.Sequential(
    nn.Linear(8, 16),  # First linear layer
    nn.Linear(16, 12),  # Second linear layer
    nn.Linear(12, 4)   # Third linear layer
)

# Dummy input and loss for the sake of the example
input_tensor = torch.randn((1, 8))  # Random input tensor
target = torch.tensor([0])  # Random target label

# Define a loss function
criterion = nn.CrossEntropyLoss()

# Forward pass
output = model(input_tensor)
loss = criterion(output, target.unsqueeze(0))

# Backward pass to compute gradients
loss.backward()

# Define a learning rate
lr = 0.01

# Access the weights
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weights of each linear layer
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

# Update the weights using the learning rate and the gradients
with torch.no_grad():  # Ensure gradients are not tracked during this operation
    weight0.data = weight0.data - lr * grads0
    weight1.data = weight1.data - lr * grads1
    weight2.data = weight2.data - lr * grads2

# Clear the gradients after updating
model.zero_grad()

# Print the updated weights (just to verify)
print("Updated weights for layer 0:", model[0].weight)
print("Updated weights for layer 1:", model[1].weight)
print("Updated weights for layer 2:", model[2].weight)


RuntimeError: 0D or 1D target tensor expected, multi-target not supported